version: '3'

services:
  web:
    image: httpd
    container_name: web
    tty: true
    ports:
      - "8000:80"
    volumes:
      - "./apache2/httpd.conf:/usr/local/apache2/conf/httpd.conf"
    depends_on:
      - api

  curltest:
    build: ./dockerfiles/curltest
    container_name: curltest
    tty: true
    depends_on:
      - api

  api:
    build: dockerfiles/api
    container_name: api
    tty: true
    expose:
      - 8888

